import nextBase from 'eslint-config-next';

export default [
  ...nextBase,
  {
    files: ['**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/ban-ts-comment': 'off',
    },
    ignores: [
      'app/domains/**',
      'app/infrastructure/**',
      'app/hooks/**',
      'app/lib/**',
      'app/store/**',
      'app/strategy-optimization-example.ts',
      'app/performance-examples.ts',
      'app/performance-quickstart.ts',
      'app/WinningTradingSystem.ts',
      'app/types/__tests__/**',
      '**/__tests__/**',
      '**/*.test.ts',
      '**/*.test.tsx',
      '**/*.spec.ts',
      '**/*.spec.tsx',
      '**/example*.ts',
      '**/example*.tsx',
      '**/examples/**',
      '**/Demo*.ts',
      '**/Demo*.tsx',
      '**/demo/**',
      '**/template/**',
      '**/fixtures.ts',
      '**/mock-*.ts',
      '**/testing/**',
      '**/test-*.ts',
      'node_modules/',
      '.next/',
      'out/',
      'dist/',
      'build/',
      'coverage/',
      'eslint.config.*',
    ],
  },
];
