/**
 * Technical Indicator Configuration Constants
 *
 * 全技術指標の設定を一元化
 * Issue #522 - 定数一元化
 */

/**
 * Comprehensive technical indicator parameters
 */
export const TECHNICAL_INDICATORS = {
  // RSI (Relative Strength Index)
  RSI_PERIOD: 14,
  RSI_OVERSOLD: 30,
  RSI_OVERBOUGHT: 70,
  RSI_EXTREME_OVERSOLD: 20,
  RSI_EXTREME_OVERBOUGHT: 80,

  // SMA (Simple Moving Average)
  SMA_PERIOD_SHORT: 10,
  SMA_PERIOD_MEDIUM: 50,
  SMA_PERIOD_LONG: 200,

  // EMA (Exponential Moving Average)
  EMA_PERIOD: 12,

  // Bollinger Bands
  BB_PERIOD: 20,
  BB_STD_DEV: 2,
  BB_UPPER_COLOR: 'rgba(59, 130, 246, 0.5)',
  BB_UPPER_BACKGROUND: 'rgba(59, 130, 246, 0.1)',
  BB_LOWER_COLOR: 'rgba(59, 130, 246, 0.5)',

  // ATR (Average True Range)
  ATR_PERIOD: 14,
  ATR_MULTIPLIER_DEFAULT: 2,

  // MACD (Moving Average Convergence Divergence)
  MACD_FAST: 12,
  MACD_SLOW: 26,
  MACD_SIGNAL: 9,

  // ADX (Average Directional Index)
  ADX_PERIOD: 14,
  ADX_TRENDING_THRESHOLD: 25,
  ADX_RANGING_THRESHOLD: 20,

  // Stochastic
  STOCHASTIC_PERIOD: 14,

  // Williams %R
  WILLIAMS_R_PERIOD: 14,

  // Volume Profile
  VOLUME_PROFILE_BINS: 20,
  VOLUME_PROFILE_MIN_DAYS: 60,
} as const;

// Backward compatibility aliases (deprecated)
export const RSI_CONFIG = {
  DEFAULT_PERIOD: TECHNICAL_INDICATORS.RSI_PERIOD,
  OVERSOLD: TECHNICAL_INDICATORS.RSI_OVERSOLD,
  OVERBOUGHT: TECHNICAL_INDICATORS.RSI_OVERBOUGHT,
  EXTREME_OVERSOLD: TECHNICAL_INDICATORS.RSI_EXTREME_OVERSOLD,
  EXTREME_OVERBOUGHT: TECHNICAL_INDICATORS.RSI_EXTREME_OVERBOUGHT,
  PERIOD_OPTIONS: [10, 14, 20] as const,
} as const;

export const SMA_CONFIG = {
  PERIOD: 20,
  SHORT_PERIOD: TECHNICAL_INDICATORS.SMA_PERIOD_SHORT,
  MEDIUM_PERIOD: TECHNICAL_INDICATORS.SMA_PERIOD_MEDIUM,
  LONG_PERIOD: TECHNICAL_INDICATORS.SMA_PERIOD_LONG,
  PERIOD_OPTIONS: [10, 20, 50, 100] as const,
  COLOR: '#fbbf24',
  LINE_WIDTH: 2,
} as const;

export const MACD_CONFIG = {
  FAST_PERIOD: TECHNICAL_INDICATORS.MACD_FAST,
  SLOW_PERIOD: TECHNICAL_INDICATORS.MACD_SLOW,
  SIGNAL_PERIOD: TECHNICAL_INDICATORS.MACD_SIGNAL,
} as const;

export const BOLLINGER_BANDS = {
  STD_DEVIATION: TECHNICAL_INDICATORS.BB_STD_DEV,
  PERIOD: TECHNICAL_INDICATORS.BB_PERIOD,
  UPPER_COLOR: TECHNICAL_INDICATORS.BB_UPPER_COLOR,
  UPPER_BACKGROUND: TECHNICAL_INDICATORS.BB_UPPER_BACKGROUND,
  LOWER_COLOR: TECHNICAL_INDICATORS.BB_LOWER_COLOR,
} as const;

export const VOLATILITY = {
  DEFAULT_ATR_PERIOD: TECHNICAL_INDICATORS.ATR_PERIOD,
  CALCULATION_PERIOD: TECHNICAL_INDICATORS.SMA_PERIOD_MEDIUM, // 50 days
} as const;
