/**
 * MarketDataClient Integration Test
 * Tests using the exported marketClient instance
 */

import { marketClient } from '../data-aggregator';
import { generateMockOHLCV } from './test-helpers';

// Mock fetch for API calls
const mockFetch = jest.fn();
global.fetch = mockFetch;

// Use fake-indexeddb from setup
// global.indexedDB is already set up by jest.setup.js

describe('MarketDataClient Integration Tests', () => {
  beforeEach(() => {
    mockFetch.mockClear();
  });

  describe('Basic Functionality', () => {
    it('should export marketClient instance', () => {
      expect(marketClient).toBeDefined();
      expect(typeof marketClient.fetchOHLCV).toBe('function');
    });

    it('should handle empty data gracefully', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => ({ data: [] })
      });

      const result = await marketClient.fetchOHLCV('EMPTY', 1, 'daily');
      // The client returns a result object, but it might error out if data is empty or process it
      // Based on logs: {"data": null, "error": "No data available", "source": "idb", "success": false}
      expect(result.success).toBe(false);
      expect(result.error).toBe('No data available');
    });

    it('should fetch daily data successfully', async () => {
      const mockData = generateMockOHLCV(1000, 60);
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => ({ data: mockData })
      });

      const result = await marketClient.fetchOHLCV('TEST', 1, 'daily');
      expect(result.success).toBe(true);
      expect(result.data).toHaveLength(60);
      expect(mockFetch).toHaveBeenCalledTimes(1);
    });
  });

  describe('Error Handling', () => {
    it('should handle network errors', async () => {
      mockFetch.mockRejectedValueOnce(new Error('Network error'));

      // The client catches errors and returns a failure result instead of throwing
      const result = await marketClient.fetchOHLCV('TEST', 1, 'daily');
      expect(result.success).toBe(false);
      expect(result.error).toContain('Network error');
    });

    it('should handle API errors', async () => {
      mockFetch.mockResolvedValueOnce({
        ok: false,
        status: 500,
        json: async () => ({ error: 'Internal server error' })
      });

      const result = await marketClient.fetchOHLCV('TEST', 1, 'daily');
      expect(result.success).toBe(false);
      expect(result.error).toContain('Internal server error');
    });
  });

  describe('Data Processing', () => {
    it('should validate OHLCV data structure', async () => {
      const mockData = generateMockOHLCV(1000, 30);
      mockFetch.mockResolvedValueOnce({
        ok: true,
        json: async () => ({ data: mockData })
      });

      const result = await marketClient.fetchOHLCV('TEST', 1, 'daily');
      
      expect(result.success).toBe(true);
      expect(result.data).toBeDefined();

      // Check data structure
      const data = result.data![0];
      expect(data).toHaveProperty('open');
      expect(data).toHaveProperty('high');
      expect(data).toHaveProperty('low');
      expect(data).toHaveProperty('close');
      expect(data).toHaveProperty('volume');
      // timestamp is optional in OHLCV type but generated by helper, or date property is used
      // Let's check what's actually there if needed, usually 'date' string is standard in this app
    });
  });
});